/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__thecrims__0_0_1 = never;
export type PromptConfig__thecrims__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__thecrims__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__thecrims__0_0_1;
  variables: PromptVariables__thecrims__0_0_1;
  content: string;
};
export type Prompt__thecrims = {
  name: 'thecrims';
  slug: 'thecrims';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__thecrims__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    thecrims: Prompt__thecrims;
  };
  globals: Globals;
};
